-- CreateTable
CREATE TABLE "Poi" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "title" TEXT,
    "title_is_visible" BOOLEAN DEFAULT false,
    "subtitle" TEXT,
    "subtitle_is_visible" BOOLEAN DEFAULT false,
    "autor" INTEGER NOT NULL,
    "creation_date" DATETIME NOT NULL,
    "update_date" DATETIME,
    "deleted_date" DATETIME,
    "last_contributor" INTEGER,
    "is_public" BOOLEAN NOT NULL DEFAULT true,
    "is_editable" BOOLEAN NOT NULL DEFAULT false,
    "biovers" INTEGER NOT NULL,
    "radius" REAL NOT NULL,
    "style_type" TEXT NOT NULL,
    "style_stroke" BOOLEAN NOT NULL,
    "style_stroke_width" REAL NOT NULL,
    "style_fill" BOOLEAN NOT NULL,
    "style_elevation" REAL NOT NULL,
    "style_elevation_ground" REAL NOT NULL,
    "style_noise" REAL NOT NULL,
    "style_is_visible" BOOLEAN NOT NULL,
    "visible_from" REAL NOT NULL,
    "trigger_mode" TEXT NOT NULL,
    "metadata" TEXT,
    CONSTRAINT "Poi_biovers_fkey" FOREIGN KEY ("biovers") REFERENCES "Biovers" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Poi_autor_fkey" FOREIGN KEY ("autor") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Poi_last_contributor_fkey" FOREIGN KEY ("last_contributor") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
