FROM mhart/alpine-node
ARG NODE_ENV=test
ENV NODE_ENV $NODE_ENV

COPY .env.test /.env
COPY ./build /build
COPY ./prisma /prisma
COPY ./package.json /package.json
COPY ./package-lock.json /package-lock.json
RUN NODE_ENV=$NODE_ENV npm install
RUN NODE_ENV=$NODE_ENV npx prisma migrate deploy
RUN NODE_ENV=$NODE_ENV npx prisma generate
CMD ["npx", "jest", "--detectOpenHandles"]