FROM mhart/alpine-node
ARG NODE_ENV=production
ENV NODE_ENV $NODE_ENV

COPY .env /.env
COPY ./build /build
COPY ./prisma /prisma
COPY ./package.json /package.json
COPY ./package-lock.json /package-lock.json
RUN npm install
RUN npx prisma generate

CMD ["node", "build/src/index.js"]